# Generated by Django 4.2.2 on 2023-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('prof_pic', models.ImageField(upload_to='Team')),
                ('member_desc', models.TextField()),
            ],
        ),
    ]
